Repository planetarium/ninechronicles-devforum, pull requests merged in 2022-08, with the labels that each got.

#12 Merge Development
  README.md
  docs/template.md
  scenario.md
Labels: documentation, enhancement, devforum, Extra Small

#7 Launcher internal documentation translation
  docs/the-structure-and-location-of-config-json.md
Labels: launcher, Small

#18 Play 9c on x86 macOS / Linux using CI Artifacts (UNOFFICIAL SUPPORT)
  docs/how-to-play-9c-on-linux-and-mac/how-to-play-9c-on-linux-and-mac.md
  docs/how-to-play-9c-on-linux-and-mac/images/Screen_Shot_2022-06-30_at_6.49.33_PM.png
  docs/how-to-play-9c-on-linux-and-mac/images/Screenshot_20220729_190921.png
  docs/how-to-play-9c-on-linux-and-mac/images/Screenshot_20220729_191604.png
  docs/how-to-play-9c-on-linux-and-mac/images/Screenshot_20220729_1916042.png
  docs/how-to-play-9c-on-linux-and-mac/images/Screenshot_20220729_191617.png
  docs/how-to-play-9c-on-linux-and-mac/images/Screenshot_20220729_1916172.png
  docs/how-to-play-9c-on-linux-and-mac/images/Untitled 1.png
  docs/how-to-play-9c-on-linux-and-mac/images/Untitled 2.png
  docs/how-to-play-9c-on-linux-and-mac/images/Untitled 3.png
  docs/how-to-play-9c-on-linux-and-mac/images/Untitled.png
Labels: launcher, Extra Small
